jasypt:
  encryptor:
    password: thesevensky
auth-server: http://www.thesevensky.com:11111

security:
  oauth2:
    client:
      client-id: theSevenSky1
      client-secret: xy123456
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      token-info-uri: ${auth-server}/oauth/check_token

