#server:
#  port: 10086
#eureka:
#  instance:
#      hostname: eureka10086.com
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://eureka10086.com:10086/eureka/
#spring:
#  profiles:
#    active: dev
